### ISSUE TITLE
Feature: Plugin Placeholders

### ISSUE THREAD

**Issue by jonthegeek** [Gilead-BioStats/gsm.app#356]
## Feature Details
If a plugin requires some level of data that isn't ready (eg, it requires that you select a Participant), it might not load properly. It would be nice to allow the plugin to tell us that, and then display a placeholder if that requirement isn't satisfied.

## Possible Implementation
Rather than calling the plugin's `shiny$UI()` function in `mod_Plugins_UI()`, put a `shiny::uiOutput()` there that will fill with the plugin's UI when/if conditions are satisfied, and which displays a placeholder otherwise.

I'm not sure yet how to specify this in the plugin spec. I can imagine a lot of scenarios along the lines of "one of SiteID or ParticipantID needs to be non-NULL". Should we have something along these lines?
```yaml
arguments:
  all:
    - rctv_strMetricID
  any:
    - rctv_strSiteID
    - rctv_strSubjectID
  any:
    - rctv_dfAE
    - rctv_dfSAE
```

## Additional Comments
I like that we automatically detect what they use right now, based on the function signature, so it would be a little sad to me if we require them to be more specific. Maybe an option would be to just have them throw an error when something is wrong, and we do something similar to #355, but as a placeholder? It might actually end up being almost identical.
